set search_path to curated;

CREATE TABLE curated.colorectal_cancer_screening (test_name                varchar,
                                                     code                     varchar,
                                                     code_system              varchar,
                                                     is_numerator             boolean,
                                                     is_denominator_inclusion boolean,
                                                     is_denominator_exclusion boolean);

insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Tomo', '74261', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Tomo', '74262', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Tomo', '74623', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('FIT-DNA', '81528', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('FIT-DNA', 'G0464', 'HCPCS', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('FOBT', 'G0328', 'HCPCS', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('FOBT', '82270', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('FOBT', '82274', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'G0213', 'HCPCS', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'G0214', 'HCPCS', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'G0215', 'HCPCS', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'G0231', 'HCPCS', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'C18.0', 'ICD10', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'C18.1', 'ICD10', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'C18.2', 'ICD10', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'C18.3', 'ICD10', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'C18.4', 'ICD10', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'C18.5', 'ICD10', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'C18.6', 'ICD10', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'C18.7', 'ICD10', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'C18.8', 'ICD10', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'C18.9', 'ICD10', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'C19', 'ICD10', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'C20', 'ICD10', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'C21.2', 'ICD10', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'C21.8', 'ICD10', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'C78.5', 'ICD10', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'Z85.038', 'ICD10', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', 'Z85.048', 'ICD10', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', '44150', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', '44151', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', '44152', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', '44153', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', '44155', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', '44156', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', '44157', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', '44158', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', '44210', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', '44211', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Exclusion', '44212', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99201', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99202', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99203', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99204', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99205', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99211', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99212', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99213', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99214', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99215', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99341', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99342', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99343', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99344', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99345', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99347', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99348', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99349', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99350', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99386', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99387', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99396', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', '99397', 'CPT', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', 'G0402', 'HCPCS', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', 'G0438', 'HCPCS', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Denom Inclusion', 'G0439', 'HCPCS', False, True, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Flexible Sigmoidocopy', 'G0104', 'HCPCS', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Flexible Sigmoidocopy', '45330', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Flexible Sigmoidocopy', '45331', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Flexible Sigmoidocopy', '45332', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Flexible Sigmoidocopy', '45333', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Flexible Sigmoidocopy', '45334', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Flexible Sigmoidocopy', '45335', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Flexible Sigmoidocopy', '45337', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Flexible Sigmoidocopy', '45338', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Flexible Sigmoidocopy', '45340', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Flexible Sigmoidocopy', '45341', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Flexible Sigmoidocopy', '45342', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Flexible Sigmoidocopy', '45346', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Flexible Sigmoidocopy', '45347', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Flexible Sigmoidocopy', '45349', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Flexible Sigmoidocopy', '45350', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '44388', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '44389', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '44390', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '44391', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '44392', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '44393', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '44394', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '44397', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '45355', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '45378', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '45379', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '45380', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '45381', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '45382', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '45383', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '45384', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '45385', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '45386', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '45387', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '45391', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '45392', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '45393', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '44401', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '44402', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '44404', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '44405', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '44406', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', '44407', 'CPT', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', 'G0105', 'HCPCS', True, False, False);
insert into colorectal_cancer_screening (test_name, code, code_system, is_numerator, is_denominator_inclusion, is_denominator_exclusion) values ('Colonoscopy', 'G0121', 'HCPCS', True, False, False);
